ite_name: EasyQuest Documentation
site_author: Knightless Labs
site_name: https://twitter.com/knightlesslabs
repo_url: https://github.com/KnightlessLabs/EasyQuest-Docs

markdown_extensions:
- admonition
